github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/bellsoft-liberica","gcr.io/paketo-buildpacks/bellsoft-liberica"]
  register:       true
  registry_token: ${ secrets.PAKETO_BOT_GITHUB_TOKEN }

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- name:            JDK 8
  id:              jdk
  version_pattern: "^8\\.[\\d]+\\.[\\d]+"
  cpe_pattern:     "update[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/bellsoft-liberica-dependency:main
  with:
    product: liberica
    type:    jdk
    version: "8"
- name:            JRE 8
  id:              jre
  version_pattern: "^8\\.[\\d]+\\.[\\d]+"
  cpe_pattern:     "update[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/bellsoft-liberica-dependency:main
  with:
    product: liberica
    type:    jre
    version: "8"
- name:            JDK 11
  id:              jdk
  version_pattern: "11\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/bellsoft-liberica-dependency:main
  with:
    product: liberica
    type:    jdk
    version: "11"
- name:            JRE 11
  id:              jre
  version_pattern: "11\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/bellsoft-liberica-dependency:main
  with:
    product: liberica
    type:    jre
    version: "11"
- name:            Native Image 11
  id:              native-image-svm
  version_pattern: "11\\.[\\d]+\\.[\\d]+"
  purl_pattern:    "[\\d]+\\.[\\d]+\\.[\\d]+\\.?[\\d]?"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/bellsoft-liberica-dependency:main
  with:
    product: nik
    type:    core
    version: "11"
- name:            Native Image 17
  id:              native-image-svm
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/bellsoft-liberica-dependency:main
  purl_pattern:    "[\\d]+\\.[\\d]+\\.[\\d]+\\.?[\\d]?"
  with:
    product: nik
    type:    core
    version: "17"
- name:            JDK 17
  id:              jdk
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/bellsoft-liberica-dependency:main
  with:
    product: liberica
    type:    jdk
    version: "17"
- name:            JRE 17
  id:              jre
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/bellsoft-liberica-dependency:main
  with:
    product: liberica
    type:    jre
    version: "17"
- name:            JDK 19
  id:              jdk
  version_pattern: "19\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/bellsoft-liberica-dependency:main
  with:
    product: liberica
    type:    jdk
    version: "19"
- name:            JRE 19
  id:              jre
  version_pattern: "19\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/bellsoft-liberica-dependency:main
  with:
    product: liberica
    type:    jre
    version: "19"
